# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fee5f10e9968f023a1ed1784061aba993f965a4d51b8d919785ebdcc1dcbb328e9b3b4bfab7e450fc12b31f5feebf733caf6d08a59dcc8b716d8cf8b4554b059

test:
  secret_key_base: ffddf162f6ccc9cd7cf35ad973aa9e8cf5449e0df2ddc8552e6a5f80caeb21320b026ae796eb5406b7e55b24e1f99edf08d0d581fc2736365ac9aed96890a8ca

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
